apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-java
  template:
    metadata:
      labels:
        app: web-java
    spec:
      containers:
      - name: java
        image: maho/web-java:0.2
      readinessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 60
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /actuator/liveness
          port: 8080
        initialDelaySeconds: 130
        timeoutSeconds: 10
        failureThreshold: 10
